<a href="https://colab.research.google.com/github/TECH-KAVIN/DATA-SCIENCE-PROJECT-/blob/main/TASK_1_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Creating Arrays :

In [ ]:
#Creating an arrsy
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[3,2,1],[6,5,4,],[9,8,7]])
print('A\n',A,'\n B\n',B)
#Create an array of zeros
print('Zeros : ',np.zeros((3,3)))
#Create an array of ones
print('Ones : ',np.ones(5))
#Create an array with a range of values
print('Range of Array : ',np.array(np.arange(1,6)))
#Create an array with evenly spaced values.
print('Linspace : ',np.linspace(5,10,3))
#Create an identity matrix.
print('Identical matrix : ',np.eye(4))

A
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 B
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Zeros :  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones :  [1. 1. 1. 1. 1.]
Range of Array :  [1 2 3 4 5]
Linspace :  [ 5.   7.5 10. ]
Identical matrix :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##Array Information:

In [ ]:
#Returns the dimensions of the array
print("Shape : ",A.shape)
#Returns the number of dimensions
print("dimension : ",A.ndim)
#Returns the total number of elements
print("Size : ",A.size)
#Returns the data type of elements
print ("datatype : ",A.dtype)

Shape :  (3, 3)
dimension :  2
Size :  9
datatype :  int64


##Array Operations:

In [ ]:
#Element-wise addition.
print("Add : ",np.add(A,B))
#Element-wise subtraction.
print("Sub : ",np.subtract(A,B))
# Element-wise multiplication.
print("Multi : ",np.multiply(A,B))
# Element-wise division.
print("Divide : ",np.divide(A,B))
#Dot product of two arrays.
print("Dot : ",np.dot(A,B))

Add :  [[ 4  4  4]
 [10 10 10]
 [16 16 16]]
Sub :  [[-2  0  2]
 [-2  0  2]
 [-2  0  2]]
Multi :  [[ 3  4  3]
 [24 25 24]
 [63 64 63]]
Divide :  [[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]
Dot :  [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


##Array Manipulation:

In [ ]:
# Reshape an array.
print('Reshape Array : ',np.arange(25).reshape(5,5))
#Concatenate arrays.
print('Concatenate : ',np.concatenate((A,B)))
# Transpose an array.
print('Transpose Array : ',np.transpose(A))
#Split an array into sub-arrays.
print('Array Spliting : ',np.split(A,3))

Reshape Array :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Concatenate :  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 1]
 [6 5 4]
 [9 8 7]]
Transpose Array :  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Array Spliting :  [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


##Mathematical Functions:

In [ ]:
#Sum of array elements.
print('Sum : ',np.sum(A))
#Mean value of array
print('Mean : ',np.mean(A))
#Median of the array
print('Median : ',np.median(A))
#Standard deviation.
print('Standard Deviation : ',np.std(A))
#Maxmimum value
print('Maxmimum Value : ',np.max(A))
#Minimum value
print('Minimum Value : ',np.min(A))

Sum :  45
Mean :  5.0
Median :  5.0
Standard Deviation :  2.581988897471611
Maxmimum Value :  9
Minimum Value :  1


##Trigonometric Functions:

In [ ]:
#Sin of Array
print('Sin of Array : ',np.sin(A))
#Cos of Array
print('Cos of Array : ',np.cos(A))
#Tan of Array
print('Tan of Array : ',np.tan(A))

Sin of Array :  [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
Cos of Array :  [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
Tan of Array :  [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


##Inverse trigonometric functions.

In [ ]:
#inverse of sin
print('Inverse of sin : ',np.arcsin(A))
#Inverse of cos
print('Inverse of cos : ',np.arccos(A))
#Inverse of tan
print('Inverse of tan : ',np.arctan(A))

Inverse of sin :  [[1.57079633        nan        nan]
 [       nan        nan        nan]
 [       nan        nan        nan]]
Inverse of cos :  [[ 0. nan nan]
 [nan nan nan]
 [nan nan nan]]
Inverse of tan :  [[0.78539816 1.10714872 1.24904577]
 [1.32581766 1.37340077 1.40564765]
 [1.42889927 1.44644133 1.46013911]]


<ipython-input-8-b550f625e09e>:2: RuntimeWarning: invalid value encountered in arcsin
  print('Inverse of sin : ',np.arcsin(A))
<ipython-input-8-b550f625e09e>:4: RuntimeWarning: invalid value encountered in arccos
  print('Inverse of cos : ',np.arccos(A))


##Random function

In [ ]:
#Random
A=np.random.rand(2,3)
print('random : ',A)
B=np.random.randint(1,10,5)
print('random int : ',B)
np.random.shuffle(B)
print('shuffled array : ',B)

random :  [[0.78586681 0.06250043 0.64022543]
 [0.10524181 0.50692171 0.8979953 ]]
random int :  [3 2 8 4 1]
shuffled array :  [3 4 8 1 2]


##Statistical Functions:

In [ ]:
#Percentile
print('Percentile : ',np.percentile(B,A))
#Corelation Coefficient
print('Corelation Coefficient : ',np.corrcoef(A))

Percentile :  [[1.03143467 1.00250002 1.02560902]
 [1.00420967 1.02027687 1.03591981]]
Corelation Coefficient :  [[ 1.         -0.19791493]
 [-0.19791493  1.        ]]


##Linear Algebra:

In [ ]:
C = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
print('Inverse of matrix : ',np.linalg.inv(C))
#Determinant of a matrix.
print('Determinant of matrix : ',np.linalg.det(C))
#Eigenvalues and eigenvectors.
print('Eigenvalues and eigenvectors. : ',np.linalg.eig(C))

Inverse of matrix :  [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
Determinant of matrix :  -306.0
Eigenvalues and eigenvectors. :  (array([11.24862343,  5.09285054, -5.34147398]), array([[ 0.24511338,  0.75669314,  0.02645665],
       [ 0.40622202, -0.03352363, -0.84078293],
       [ 0.88028581, -0.65291014,  0.54072554]]))


In [ ]:
#Sorting
print('Sorting of array  : ',np.sort(C))

Sorting of array  :  [[ 1  1  6]
 [-2  4  5]
 [ 2  7  8]]


##File Input/Output:

In [ ]:
from tempfile import TemporaryFile
fl= TemporaryFile()

In [ ]:
# Save an array to a binary file.
np.save(fl,A)
print('file saved ')

file saved 


In [ ]:
# Load an array from a binary file.
fl.seek(0)
print('Loaded file : ',np.load(fl))

Loaded file :  [[0.78586681 0.06250043 0.64022543]
 [0.10524181 0.50692171 0.8979953 ]]


#***THE END***